---
language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.6
env:
  - PUPPET_GEM_VERSION="~> 3.0"
  - PUPPET_GEM_VERSION="~> 4.0"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0"
gemfile: .gemfile
bundler_args: --without system_tests
script:
  - "bundle exec rake validate"
  - "bundle exec rake lint"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
notifications:
  on_success: change
  on_failure: change
